### ISSUE TITLE
scnp-cli fails assert on Raspberry Pi

### ISSUE THREAD

**Issue by acli** [socratools/socradoc#8]
On a Raspberry Pi (Debian Buster, armv7l), trying to run the tool results in

    Fatal: libusb_control_transfer: !(luret_ctrl_transfer == sizeof(data))

I added some printf’s in the code to see what’s going on. luret_ctrl_transfer is 8 but sizeof(data) is 4. I checked which version of the code I had; it was from January 2, 2022.

I did a git pull; the assert also fails in the current code.

**Comment by ndim** [comment]
I have a Raspberry Pi somewhere, so I can try to replicate this with a view to fixing it. Might be Debian, might be ARM, might be Raspberry, we will see.

**Comment by ndim** [comment]
I think I have found the problem just by reading  the code i.e. without any testing at all, due to being away from my development workstation: Programmer error on the beginner level, i.e. my mistake. Sorry.

Looks like `sizeof(data)` in that check should actually be `data_size`. Armv7 pointer size (4) is different than x86_64 pointer size (8), so that assertion always matched on my x86_64 system by pure chance.

(untested, will test later)

**Comment by ndim** [comment]
https://github.com/socratools/socradoc/commit/61c4201d1bac136ac80af5fabdd22d9e75f8c907 builds and runs on both x86_64 and ARM (armv6l here), while it failed on ARM with the original error message.

However, this made me notice that the `make check` tests did NOT fail on ARM, so something is wrong with those checks which I want to figure out and fix before I merge https://github.com/socratools/socradoc/commit/61c4201d1bac136ac80af5fabdd22d9e75f8c907.

**Comment by ndim** [comment]
> However, this made me notice that the `make check` tests did NOT fail on ARM, so something is wrong with those checks which I want to figure out and fix before I merge [61c4201](https://github.com/socratools/socradoc/commit/61c4201d1bac136ac80af5fabdd22d9e75f8c907).

This issue completely unrelated. The test cases are written to only do dry runs, i.e. to only exercise the code **except for** the actual USB communication.
